plugin:
  has_options: false

  admin_tools:
    - name: laurent_bulletin_admin_tool
      class: bar-chart-o

  tools:
    - name: laurent_bulletin_tool
      is_displayable_in_workspace: false
      is_displayable_in_desktop: true
      class: bar-chart-o